name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v6

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        env:
          CI_JOB_TOKEN: ${{ secrets.CI_JOB_TOKEN }}
        run: |
          export PIP_EXTRA_INDEX_URL="https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.ifremer.fr/api/v4/projects/4991/packages/pypi/simple"
          pip install -e ".[dev]"

      - name: Run style checks
        run: |
          make check-codestyle

      - name: Run tests
        run: |
          make test

      - name: Run safety checks
        run: |
          make check-safety
